http://localhost:3000/register/
###

POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "test2",
  "name": "Adam Richard",
  "password": "test@222",
  "gender": "male",
  "location": "Detroit"
}

###
POST http://localhost:3000/login/
Content-Type: application/json 

{
  "username": "test2",
  "password": "test@222"
}

###
PUT http://localhost:3000/login/
Content-Type: application/json 

{
  "username": "test1",
  "oldPassword": "test@111",
  "newPassword": "test@456"
}