http://localhost:3000/register/
###

POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "nikhil",
  "name": "Adam Richard",
  "password": "hello123",
  "gender": "male",
  "location": "Detroit"
}

###
POST http://localhost:3000/login/
Content-Type: application/json 

{
  "username": "nikhil22",
  "password": "hello123"
}

###
PUT http://localhost:3000/login/
Content-Type: application/json 

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}